### ISSUE TITLE
Consider adding Pants to the list of tools

### ISSUE THREAD

**Issue by cczona** [nrwl/monorepo.tools#52]
Pants is a polyglot open source monorepo build system. It currently supports Python, Go, Java, Scala, and Shell. Adding JavaScript support is high on the community roadmap's priority list. Pants is a BUILD-file oriented system with a design inspired by Blaze, Ant, and others. It is most frequently compared to Bazel; which is reasonable, though there are a number of key differences between the two: https://blog.pantsbuild.org/pants-vs-bazel/ 

More info is available at https://pantsbuild.org and https://slack.pantsbuild.org. As a team member, I'm happy to answer questions. Thanks for welcoming the project to be submitted for your consideration! https://twitter.com/juristr/status/1514642911492640771?s=20&t=-YfS5beID6oxDqQhLM83zQ

**Comment by bcabanes** [comment]
Hi @cczona!

For sure a PR is gladly welcomed! Let me know if you need help with it.

**Comment by bcabanes** [comment]
Thank you for the PR! I commented and updated it, let me know!

**Comment by benjyw** [comment]
Thanks for the quick turnaround, and for the updates, which definitely look a lot better than my attempt :)

I commented with a couple more questions to be sure I understand the categories correctly, so that I can ensure that our content make sense.

**Comment by bcabanes** [comment]
Answered! Hope it helps!

**Comment by benjyw** [comment]
Thanks for clarifying. Looks like our existing answers make sense with those clarifications. :)

**Comment by benjyw** [comment]
Thanks! Closed in https://github.com/nrwl/monorepo.tools/pull/57

**Comment by benjyw** [comment]
@cczona can you close the issue out?

**Comment by bcabanes** [comment]
I just merged the PR, it will be live in a few minutes, the time for CI to pass and deploy to happen. 👍 

Closing the issue.
